#!/bin/bash -e

#SBATCH --job-name ASMQC
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --output pfr_assemblyqc.stdout
#SBATCH --error pfr_assemblyqc.stderr
#SBATCH --mem=4G

full_test_flag=0
v3_hic_test_flag=0

if [ "$#" -gt 1 ]; then
    echo "Usage: $0 [-t] [-h]"
    echo "  -t: Run test_full profile"
    echo "  -h: Run Hi-C test"
    exit 1
fi

# Parse command line options
while getopts "th" opt; do
    case ${opt} in
    t )
        full_test_flag=1
        ;;
    h )
        v3_hic_test_flag=1
        ;;
    \? )
        echo "Invalid option: $OPTARG" 1>&2
        exit 1
        ;;
    esac
done
shift $((OPTIND -1))

ml unload perl
ml apptainer/1.1
ml nextflow/24.10.6

export TMPDIR="/workspace/$USER/tmp"
export APPTAINER_BINDPATH="$APPTAINER_BINDPATH,$TMPDIR:$TMPDIR,$TMPDIR:/tmp"

if [ $full_test_flag -eq 1 ]; then
    nextflow \
        main.nf \
        -c pfr/profile.config \
        -profile pfr,apptainer,test_full \
        --ncbi_fcs_gx_skip false \
        --ncbi_fcs_gx_db_path "/workspace/ComparativeDataSources/NCBI/FCS/GX/r2023-01-24" \
        --kraken2_skip false \
        --kraken2_db_path "/workspace/ComparativeDataSources/kraken2db/k2_pluspfp_20240904" \
        -resume \
        --outdir results
elif [ $v3_hic_test_flag -eq 1 ]; then
    nextflow \
        main.nf \
        -c pfr/profile.config \
        -profile pfr,apptainer \
        -params-file /workspace/assemblyqc/testdata/v3-hic/data/params.json \
        -resume \
        --outdir results
else
    nextflow \
        main.nf \
        -c pfr/profile.config \
        -profile pfr,apptainer \
        -params-file pfr/params.json \
        -resume
fi
